function mmn_trialstats_check( options )
%tayeeg_trialstats_check Performs all quality checks for trial statistics.
%   IN:     optionally:
%           options         - the struct that contains all analysis options
%   OUT:    -

if nargin < 1
    options = tayeeg_analysis_options;
end

if ~exist(options.qualityroot, 'dir')
    mkdir(options.qualityroot);
end

for idCell = options.subjectIDs
    id = char(idCell);
% Collect trial numbers
[nTrialsInitial,nEyeblinks,nArtefacts,...
    nBadChannels,nGoodTrialsTone,nEyeartefactsTone] = mmn_trial_statistics( id, options );
end

%% Plot Trial Statistics
% Eye-blink treatment
% table and plot
switch options.eeg.preproc.eyeCorrMethod
    case 'reject'
        % table
        trialStatsTable = table(nTrialsInitial', ...
            nEyeblinks', ...
            nEyeartefactsTone',...
            nArtefacts', nBadChannels', ...
            nGoodTrialsTone', ...
            'RowNames', options.subjectIDs', ...
            'VariableNames', {'nTrialsInitial', ...
            'nEyeblinks', ...
            'nEyeartefactsTone',...
            'nAdditionalArtefacts', 'nBadChannels', ...
            'nGoodTrialsTone'});
        % plot
        fh = mmn_plot_overview_trial_statistics(options.subjectIDs, nTrialsInitial, ...
            nEyeblinks, nArtefacts, nBadChannels, nGoodTrialsTone, nEyeartefactsTone);
        
    case 'ssp'
        % table
        trialStatsTable = table(nTrialsInitial', ...
            nEyeblinks', ...
            nArtefacts', nBadChannels', ...
            nGoodTrialsTone', ...
            'RowNames', options.subjectIDs', ...
            'VariableNames', {'nTrialsInitial', ...
            'nEyeblinks', ...
            'nAdditionalArtefacts', 'nBadChannels', ...
            'nGoodTrialsTone'});
        % plot
        fh = mmn_plot_overview_trial_statistics(options.subjects.all, nTrialsInitial, ...
            nEyeblinks, nArtefacts, nBadChannels, nGoodTrialsTone);
        
end

if ~exist(options.qualityroot, 'dir')
    mkdir(options.qualityroot);
end

save(options.eeg.quality.trialstatstab, 'trialStatsTable');
saveas(fh, options.eeg.quality.trialstatsfig, 'png');
end
