function stats_secondlevel             = mmn_select_stats_group(options)

stats_secondlevel.secondlevelDir.classical = ...
    fullfile(options.eeg.preproc.grouproot, 'stats_model', [options.eeg.part '_' options.eeg.stats.firstLevelDesign]);
stats_secondlevel.secondlevel_eyeblinksDir = [stats_secondlevel.secondlevelDir.classical '_Corrected_Eyeblinks'];
stats_secondlevel.secondlevelDesign        =  options.eeg.stats.firstLevelDesign;
stats_secondlevel.secondlevelAnalysisTemplate.classical ...
    = fullfile(options.eeg.batchesroot, 'secondLevel_cov_template.m');
stats_secondlevel.secondlevelAnalysisTemplate.bayesian ...
    = fullfile(options.eeg.batchesroot, 'secondLevel_cov_template_bayesian.m');
stats_secondlevel.secondlevelAnalysisTemplate.nonparametric ...
    = fullfile(options.eeg.batchesroot, 'secondLevel_cov_template_nonparametric.m');

stats_secondlevel.secondlevelAnalysisTemplate.anova    ...
    = fullfile(options.eeg.batchesroot, 'anova_test_job.m');
stats_secondlevel.secondlevelAnalysisTemplate.full     ...
    = fullfile(options.eeg.batchesroot, 'fullfactorial.m');
stats_secondlevel.secondlevelDataType ...
    = 'sensor_';
stats_secondlevel.secondlevelAnalysisType ...
    = 'classical';
stats_secondlevel.secondlevelStatsThreshold = 'cluster';
end